title: Dain's tech blog 
description: "Exploring Medical AI and Healthcare Technology | Research notes and insights on healthcare domain-specific AI models | Contact: eundain94@gmail.com"
baseurl: ""
url: "https://astrodyn94.github.io"
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
